[extend]
useDefault = true

[[paths]]
  path = '''^\.github/.*$'''
  ignore = true

[[paths]]
  path = '''^database/.*$'''
  ignore = true

[[paths]]
  path = '''^docs/.*$'''
  ignore = true

[[paths]]
  path = '''^[^/]+$'''
  ignore = true

[[paths]]
  path = '''.*\.env\.example'''
  ignore = true