version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: mentorapredict_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mentorapredict
      POSTGRES_PASSWORD: mentorapredict
      POSTGRES_DB: mentorapredict
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    container_name: mentorapredict_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mentor
      MONGO_INITDB_ROOT_PASSWORD: mentor
      MONGO_INITDB_DATABASE: mentorapredict
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: mentorapredict_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--appendonly", "no"]

volumes:
  postgres-data:
  mongo-data:
