packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
allowBuilds:
  "@nestjs/core": true
  "@scarf/scarf": true
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: false
  sharp: true
