packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
allowBuilds:
  "@nestjs/core": true
  "@scarf/scarf": true
  electron: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: true
